# Generated by Django 3.2.8 on 2021-12-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(default='123456', max_length=64)),
                ('email', models.EmailField(default='123456789@gmail.com', max_length=254)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_name', 'email'), name='unique_user'),
        ),
    ]
