# Generated by Django 3.2.8 on 2021-12-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211221_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelimg',
            name='user',
        ),
        migrations.AddField(
            model_name='labelimg',
            name='publish_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
