# Generated by Django 3.2.8 on 2021-12-22 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_publish_user_labelimg_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
        migrations.RemoveField(
            model_name='labelimg',
            name='user',
        ),
        migrations.AddField(
            model_name='labelimg',
            name='claim_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_task', to='backend.userinfo'),
        ),
        migrations.AddField(
            model_name='labelimg',
            name='publish_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulish_task', to='backend.userinfo'),
        ),
        migrations.AlterField(
            model_name='labelimg',
            name='img',
            field=models.ImageField(max_length=1000, upload_to='uploads/None/'),
        ),
    ]
