# Generated by Django 3.2.8 on 2021-12-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211222_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelimg',
            name='task_name',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='labelimg',
            name='img',
            field=models.ImageField(max_length=1000, upload_to='D:\\杨心妤\\大学\\大三\\大三上\\BS\\project\\没想到吧又重来了\\BS-project-ImmageAnnotation-Web\\backend/upload_file/uploadsNone/img/'),
        ),
        migrations.AlterField(
            model_name='labelimg',
            name='publish_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_task', to='backend.userinfo'),
        ),
    ]
