# Generated by Django 3.2.8 on 2021-12-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211222_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelimg',
            name='claim_user',
        ),
        migrations.RemoveField(
            model_name='labelimg',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labelimg',
            name='publish_user',
        ),
        migrations.AlterField(
            model_name='labelimg',
            name='img',
            field=models.ImageField(max_length=1000, upload_to='D:\\杨心妤\\大学\\大三\\大三上\\BS\\project\\最后一次重开\\backend/upload_file/uploads//img/'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='NULL', max_length=20)),
                ('description', models.TextField(default='NULL', max_length=1000)),
                ('status', models.CharField(default='未领取', max_length=20)),
                ('claim_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_task', to='backend.userinfo')),
                ('publish_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_task', to='backend.userinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='labelimg',
            name='task_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_task', to='backend.task'),
        ),
    ]
