# Generated by Django 3.2.8 on 2021-12-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211224_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelimg',
            name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_img', to='backend.labelimg'),
        ),
    ]
